### ISSUE TITLE
The logo is not the best for browser, or for tab

### ISSUE THREAD

**Issue by pekrau** [pekrau/BeerClub#95]
The text on top of the new logo does not show up very well in the browser or in its tab.

Is this a problem with Google Chrome? Some kind of conditional get of the image file that does not work?

Ping @ewels Many thanks by the way! Aren't you having parental leave?

(I have not deployed this on beerclub.scilifelab.se, only on my laptop so far.)

**Comment by ewels** [comment]
Hmm sorry, I should have tested locally. I was multitasking with babies 🍼 😅 

I'll try to deploy locally and take a look 👍

**Comment by ewels** [comment]
Ok I tried but wasn't able to deploy locally. I think a `settings.py` file is missing from the repo?

**Comment by pekrau** [comment]
I am in a meeting today. Will look at it later.

Multitasking with babies, I was wondering about that...

/Per K

Den tis 21 maj 2019 11:06Phil Ewels <notifications@github.com> skrev:

**Comment by pekrau** [comment]
OK, @ewels  now I have refreshed my memory. It's like this:

- There is no `settings.py`; it is a dictionary in `__init__.py`
- This dictionary is updated by the contents of a file `settings.json`, which must be in the same dir as the main code.
- This happens in `utils.setup`
- There is a template settings file `template_settings.json` as help.
